name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set Locale to Chinese
        run: echo "LANG=zh_CN.UTF-8" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App0.0 v__VERSION__"
          releaseBody: "更新测试"
          releaseDraft: true
          prerelease: false
      
      - name: Find and save signature file
        run: |
          SIGNATURE_FILE=$(find src-tauri/target/release/bundle/macos/ -name "*.sig")
          echo "TAURI_SIGNATURE=$(cat $SIGNATURE_FILE)" >> $GITHUB_ENV

      - name: Update update.json with signature
        run: sed -i "s|\"signature\": null|\"signature\": \"${TAURI_SIGNATURE}\"|g" src-tauri/target/release/bundle/macos/update.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: src-tauri/target/release/bundle/macos/
