name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    outputs:
      artifact_paths: ${{ steps.myAction.outputs.artifactPaths }}
      filtered_paths_mac: ${{ steps.sigActionMac.outputs.filteredPathsMac }}
      filtered_msi_paths_win: ${{ steps.sigActionWin.outputs.filteredMsiPathsWin }}
      filtered_nsis_paths_win: ${{ steps.sigActionWin.outputs.filteredNsisPathsWin }}

    steps:
      - name: Set Locale to Chinese
        run: echo "LANG=zh_CN.UTF-8" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        id: myAction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App0.0 v__VERSION__"
          releaseBody: "更新测试"
          releaseDraft: true
          prerelease: false

      - name: Get Action Output(macos only)
        id: sigActionMac
        if: matrix.platform == 'macos-latest'
        run: |
          output_path='${{ steps.myAction.outputs.artifactPaths }}'
          filtered_paths_mac=$(echo "$output_path" | jq -r '.[] | select(endswith(".sig"))')
          echo "Filtered Output Paths: $filtered_paths_mac"
          echo "::set-output name=filtered_paths_mac::${filtered_paths_mac}"

      - uses: actions/upload-artifact@v3
        name: Upload Sig(macos only)
        if: matrix.platform == 'macos-latest'
        with:
          name: 应用名.app.tar.gz.sig
          path: ${{ steps.sigActionMac.outputs.filtered_paths_mac }}

      - name: Get Action Output(windows only)
        id: sigActionWin
        if: matrix.platform == 'windows-latest'
        run: |
          $output_path = '${{ steps.myAction.outputs.artifactPaths }}'
          $paths = $output_path | ConvertFrom-Json
          $sig_paths = $paths | Where-Object { $_ -match '\.sig$' }
          $first_path = $sig_paths[0]
          $second_path = $sig_paths[1]
          echo "##[set-output name=filtered_msi_path_win;]$first_path"
          echo "##[set-output name=filtered_nsis_paths_win;]$second_path"

      - uses: actions/upload-artifact@v3
        name: Upload Msi Sig(windows only)
        if: matrix.platform == 'windows-latest'
        with:
          name: 应用名_x64_zh-CN.msi.zip.sig
          path: ${{ steps.sigActionWin.outputs.filtered_msi_paths_win }}

      - uses: actions/upload-artifact@v3
        name: Upload Nsis Sig(windows only)
        if: matrix.platform == 'windows-latest'
        with:
          name: 应用名_x64-setup.nsis.zip.sig
          path: ${{ steps.sigActionWin.outputs.filtered_nsis_paths_win }}
