name: Build and Package Tauri App

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: install os dependencies(linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: install os dependencies(macos only)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install rust
      - name: install os dependencies(windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install gtk-runtime webkitgtk librsvg
      - name: pnpm Install dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Package for ${{ matrix.os }}
        run: pnpm tauri build --target ${{ matrix.os }}
